# Generated by Django 5.0 on 2023-12-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
