# Generated by Django 5.0 on 2023-12-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorite_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_id', models.IntegerField(unique=True)),
                ('name', models.CharField()),
                ('favorites_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorite_app.favorite')),
            ],
        ),
    ]
