# Generated by Django 5.0 on 2023-12-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_id',
            field=models.CharField(unique=True),
        ),
    ]
