# Generated by Django 5.0 on 2023-12-12 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_app', '0002_alter_cocktail_cocktail_id'),
        ('favorite_app', '0005_alter_favorite_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='favorites_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktails', to='favorite_app.favorite'),
        ),
    ]
